<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DataDictionaryIE [
<!ELEMENT DataDictionaryIE (DataElementIE*)>
<!ELEMENT DataElementIE (Name,IE)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT IE (#PCDATA)>
]>

<DataDictionaryIE xmlns:Dicom="http://www.nema.org/medical/dicom">
	<DataElementIE><Name>ReferencedFrameNumber</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ReferencedSegmentNumber</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>TypeOfInstances</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ReferencedSOPSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DICOMRetrievalSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DICOMMediaRetrievalSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>WADORetrievalSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>XDSRetrievalSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>WADORSRetrievalSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ReferencedSeriesSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PrimaryAnatomicStructureSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AnatomicRegionSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AnatomicRegionModifierSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PrimaryAnatomicStructureModifierSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RequestedProcedureID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>RequestedProcedureDescription</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>RequestedProcedureCodeSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ReasonForTheRequestedProcedure</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ReasonForRequestedProcedureCodeSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ScheduledProcedureStepID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ScheduledProcedureStepDescription</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ScheduledProtocolCodeSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PixelSpacing</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelSpacingCalibrationType</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelSpacingCalibrationDescription</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterShape</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterLeftVerticalEdge</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterRightVerticalEdge</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterUpperHorizontalEdge</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterLowerHorizontalEdge</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CenterOfCircularShutter</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RadiusOfCircularShutter</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>VerticesOfThePolygonalShutter</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterPresentationValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ShutterPresentationColorCIELabValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContentLabel</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContentDescription</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ConceptNameCodeSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AlternateContentDescriptionSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>UserContentLabel</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>UserContentLongLabel</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContentCreatorName</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContentCreatorIdentificationCodeSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>Rows</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>Columns</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BitsStored</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>LossyImageCompression</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>LossyImageCompressionRatio</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>LossyImageCompressionMethod</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PerformedProcedureStepID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformedProcedureStepStartDate</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformedProcedureStepStartTime</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformedProcedureStepEndDate</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformedProcedureStepEndTime</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformedProcedureStepDescription</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformedProtocolCodeSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>CommentsOnThePerformedProcedureStep</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ExposureIndex</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>TargetExposureIndex</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DeviationIndex</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ViewCodeSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SliceProgressionDirection</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SourcePatientGroupIdentificationSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>GroupOfPatientsIdentificationSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>UniqueDeviceIdentifier</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>DeviceDescription</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ReferencedDefinedProtocolSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ReferencedPerformedProtocolSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PatientName</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>TypeOfPatientID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientBirthDate</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientBirthDateInAlternativeCalendar</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientDeathDateInAlternativeCalendar</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientAlternativeCalendar</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientSex</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ReferencedPatientPhotoSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>QualityControlSubject</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ReferencedPatientSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientBirthTime</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>OtherPatientIDsSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>OtherPatientNames</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>EthnicGroup</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>EthnicGroupCodeSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientComments</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientSpeciesDescription</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientSpeciesCodeSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientBreedDescription</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientBreedCodeSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>BreedRegistrationSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>StrainDescription</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>StrainNomenclature</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>StrainCodeSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>StrainAdditionalInformation</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>StrainStockSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>GeneticModificationsSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ResponsiblePerson</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ResponsiblePersonRole</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ResponsibleOrganization</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>PatientIdentityRemoved</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>DeidentificationMethod</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>DeidentificationMethodCodeSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSponsorName</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialProtocolID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfClinicalTrialProtocolID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>OtherClinicalTrialProtocolIDsSequence</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialProtocolName</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSiteID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfClinicalTrialSiteID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSiteName</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSubjectID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfClinicalTrialSubjectID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSubjectReadingID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfClinicalTrialSubjectReadingID</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialProtocolEthicsCommitteeName</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialProtocolEthicsCommitteeApprovalNumber</Name><IE>PATIENT</IE></DataElementIE>
	<DataElementIE><Name>StudyDate</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>StudyTime</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ReferringPhysicianName</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ReferringPhysicianIdentificationSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ConsultingPhysicianName</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ConsultingPhysicianIdentificationSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>StudyID</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>StudyDescription</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PhysiciansOfRecord</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PhysiciansOfRecordIdentificationSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>NameOfPhysiciansReadingStudy</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PhysiciansReadingStudyIdentificationSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>RequestingService</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>RequestingServiceCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ProcedureCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ReasonForPerformedProcedureCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>AdmittingDiagnosesDescription</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>AdmittingDiagnosesCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PrincipalDiagnosisCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PrimaryDiagnosisCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>SecondaryDiagnosesCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>HistologicalDiagnosesCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientAge</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientSize</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientWeight</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientBodyMassIndex</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>MeasuredAPDimension</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>MeasuredLateralDimension</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientSizeCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>MedicalAlerts</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>Allergies</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>SmokingStatus</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PregnancyStatus</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>LastMenstrualDate</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientState</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>Occupation</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>AdditionalPatientHistory</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>AdmissionID</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfAdmissionID</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfAdmissionIDSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ReasonForVisit</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ReasonForVisitCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ServiceEpisodeID</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfServiceEpisodeIDSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ServiceEpisodeDescription</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>PatientSexNeutered</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialTimePointID</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfClinicalTrialTimePointID</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialTimePointDescription</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialTimePointTypeCodeSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>LongitudinalTemporalOffsetFromEvent</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>LongitudinalTemporalEventType</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>ConsentForClinicalTrialUseSequence</Name><IE>STUDY</IE></DataElementIE>
	<DataElementIE><Name>Modality</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SeriesNumber</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>Laterality</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SeriesDate</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SeriesTime</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformingPhysicianName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PerformingPhysicianIdentificationSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ProtocolName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SeriesDescription</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SeriesDescriptionCodeSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>OperatorsName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>OperatorIdentificationSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ReferencedPerformedProcedureStepSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>RelatedSeriesSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>BodyPartExamined</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SmallestPixelValueInSeries</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>LargestPixelValueInSeries</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>RequestAttributesSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>AnatomicalOrientationType</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialCoordinatingCenterName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSeriesID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>IssuerOfClinicalTrialSeriesID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ClinicalTrialSeriesDescription</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>FrameOfReferenceUID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PositionReferenceIndicator</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>Manufacturer</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>StationName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>InstitutionalDepartmentName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>InstitutionalDepartmentTypeCodeSequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ManufacturerModelName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ManufacturerDeviceClassUID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>DeviceSerialNumber</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SoftwareVersions</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>GantryID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>UDISequence</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>DeviceUID</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>SpatialResolution</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>DateOfManufacture</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>DateOfInstallation</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>DateOfLastCalibration</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>TimeOfLastCalibration</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PixelPaddingValue</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>ReferencedInstanceSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DerivationDescription</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DerivationCodeSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SourceImageSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SourceInstanceSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionUID</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionNumber</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionDate</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionDateTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImagesInAcquisition</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>IrradiationEventUID</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PatientOrientation</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContentDate</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContentTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImageType</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImageComments</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>QualityControlImage</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BurnedInAnnotation</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RecognizableVisualFeatures</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>IconImageSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PresentationLUTShape</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RealWorldValueMappingSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImageLaterality</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImageOrientationPatient</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImagePositionPatient</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SliceThickness</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SpacingBetweenSlices</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SliceLocation</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SamplesPerPixel</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PhotometricInterpretation</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BitsAllocated</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>HighBit</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelRepresentation</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PlanarConfiguration</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelAspectRatio</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SmallestImagePixelValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>LargestImagePixelValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RedPaletteColorLookupTableDescriptor</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>GreenPaletteColorLookupTableDescriptor</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BluePaletteColorLookupTableDescriptor</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RedPaletteColorLookupTableData</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>GreenPaletteColorLookupTableData</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BluePaletteColorLookupTableData</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ICCProfile</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ColorSpace</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelData</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FloatPixelData</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FloatPixelPaddingValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FloatPixelPaddingRangeLimit</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DoubleFloatPixelData</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DoubleFloatPixelPaddingValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DoubleFloatPixelPaddingRangeLimit</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelDataProviderURL</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PixelPaddingRangeLimit</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ExtendedOffsetTable</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ExtendedOffsetTableLengths</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusAgent</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusAgentSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusRoute</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusAdministrationRouteSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusVolume</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusStartTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusStopTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusTotalDose</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastFlowRate</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastFlowDuration</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusIngredient</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ContrastBolusIngredientConcentration</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PreferredPlaybackSequencing</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FrameTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FrameTimeVector</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>StartTrim</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>StopTrim</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RecommendedDisplayFrameRate</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CineRate</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FrameDelay</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImageTriggerDelay</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>EffectiveDuration</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ActualFrameDuration</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>MultiplexedAudioChannelsDescriptionCodeSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>NumberOfFrames</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>FrameIncrementPointer</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>StereoPairsPresent</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ConcatenationFrameOffsetNumber</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RepresentativeFrameNumber</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SOPInstanceUIDOfConcatenationSource</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>InConcatenationNumber</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DimensionOrganizationSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DimensionOrganizationType</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DimensionIndexSequence</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CardiacSynchronizationTechnique</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CardiacSignalSource</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CardiacRRIntervalSpecified</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CardiacBeatRejectionTechnique</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>LowRRValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>HighRRValue</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>IntervalsAcquired</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>IntervalsRejected</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RespiratoryMotionCompensationTechnique</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RespiratorySignalSource</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RespiratoryTriggerDelayThreshold</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RespiratoryTriggerType</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BulkMotionCompensationTechnique</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>BulkMotionSignalSource</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImageToEquipmentMappingMatrix</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>EquipmentCoordinateSystemIdentification</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CollimatorGridName</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PlateType</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>PhosphorType</Name><IE>SERIES</IE></DataElementIE>
	<DataElementIE><Name>KVP</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>PlateID</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DistanceSourceToDetector</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DistanceSourceToPatient</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ExposureTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>XRayTubeCurrent</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>Exposure</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ExposureInuAs</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ImagerPixelSpacing</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>GeneratorPower</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionDeviceProcessingDescription</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>AcquisitionDeviceProcessingCode</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CassetteOrientation</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>CassetteSize</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ExposuresOnPlate</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RelativeXRayExposure</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>Sensitivity</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>MultienergyCTAcquisition</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RescaleIntercept</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RescaleSlope</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RescaleType</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ScanOptions</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DataCollectionDiameter</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>DataCollectionCenterPatient</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>ReconstructionTargetCenterPatient</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>TableHeight</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RotationDirection</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>RevolutionTime</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>SingleCollimationWidth</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>TotalCollimationWidth</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>TableSpeed</Name><IE>INSTANCE</IE></DataElementIE>
	<DataElementIE><Name>TableFeedPerRotation</Name><IE>INSTANCE</IE></DataElementIE>